apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.nginxName" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "app-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http