apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.multitoolName" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: multitool
spec:
  type: {{ .Values.multitool.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: multitool
  ports:
    - name: http
      port: {{ .Values.multitool.service.port }}
      targetPort: 8080