apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.nginxName" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: 80