nameOverride: ""
fullnameOverride: ""

nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

multitool:
  replicaCount: 1
  image:
    repository: wbitt/network-multitool
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    HTTP_PORT: "8080"